### ISSUE TITLE
tukit open print garbage

### ISSUE THREAD

**Issue by lnussel** [openSUSE/transactional-update#115]
tukit open is supposed to print the id of the transaction. It's also dumping log output and prepends "ID:"  which requires a silly parser. It should just print the number and nothing else.

**Comment by laenion** [comment]
If you want to process the output you should use the `-q` option, then you won't see the log output, but just the line with the transaction id.

Regarding the prepended _ID:_ string: That was done because just spitting out some string without explanation looks strange from a user's perspective. However it should be really easy to just drop the first 4 characters of a string in any language.
Moreover the `tukit` command is mainly meant to be used by an admin to access the libraries functionality. For processing the output in scripts using the D-Bus interface is probably the better way.

**Comment by lnussel** [comment]
:facepalm:

**Comment by lnussel** [comment]
For completeness, this is now such an output looks like (all stdout):
```
 # tukit open
2023-10-12 09:57:41 tukit 4.4.0 started
2023-10-12 09:57:41 Options: open 
2023-10-12 09:57:44 Using snapshot 679 as base for new snapshot 680.
2023-10-12 09:57:44 Syncing /etc of previous snapshot 678 as base into new snapshot "/.snapshots/680/snapshot"
2023-10-12 09:57:44 SELinux is enabled.
Relabeled /var/lib/machines from system_u:object_r:unlabeled_t:s0 to system_u:object_r:systemd_machined_var_lib_t:s0
setxattr failed: /var/lib/machines: Operation not supported
ID: 680
2023-10-12 09:57:46 Transaction completed.
```
So that is really weird. Something like this should be entirely sufficient:
```
# tukit open
Opened transaction 680
```
And then maybe for machines

```
# tukit -q open
680
```

But that's about it. The log output can be enabled optionally using some --debug switch and log to stderr.
If there is software that relies on this behavior then please fix it. What other consumer other than transactional-update is crazy enough to parse this mess anyway?
