### ISSUE TITLE
fail snapshot if snapper fails to set it as default

### ISSUE THREAD

**Issue by lnussel** [openSUSE/transactional-update#118]
snapper now returns failures from plugins. That is important with systemd-boot. It could happen that the ESP runs out of space for example. In that case sdbootutil would fail to copy the kernel to the ESP and signal failure to snapper which in turn exits with code != 0. Transactional-update must then consider the snapshot as failed as it wouldn't boot.

**Comment by lnussel** [comment]
ping?

**Comment by laenion** [comment]
Implementing now.

**Comment by laenion** [comment]
If _snapper_ returns with an error code an exception will be thrown, which in turn will result in the snapshot being deleted again (see https://github.com/openSUSE/transactional-update/blob/master/lib/Snapshot/Snapper.cpp).
There are two exceptions: `setDefault` and `setReadOnly` will try to use _btrfs_ directly if snapper failed; this is for compatibility with older snapper versions, e.g. during version updates.

I guess the later is causing a problem because then the snapper plugins won't be executed any more?

**Comment by lnussel** [comment]
yes. If snapper fails but t-u still treats the snapshot as good, the snapshot may not be bootable

**Comment by laenion** [comment]
Added with transactional-update 4.6.0.
