### ISSUE TITLE
How to stop update resetting transactional-update.conf?

### ISSUE THREAD

**Issue by kevinsmia1939** [openSUSE/transactional-update#27]
I change 
REBOOT_METHOD=auto to REBOOT_METHOD=none
in usr/etc/transactional-update.conf

But after some update it change back to auto. This leads to my PC unexpectedly reboot. I want to keep it at none. 

Thanks.

**Comment by thkukuk** [comment]
Sounds like you edited /usr/etc/transactional-update.conf, how did you did this since the filesystem should be read-only?
/usr/etc is for vendor provided default configuration, you need to overwrite it in /etc, see the documentation:
https://kubic.opensuse.org/documentation/transactional-update-guide/tu-files.html

So "echo REBOOT_METHOD=none >> /etc/transactional-update.conf"

**Comment by kevinsmia1939** [comment]
Thanks, I edit the wrong file.
