### ISSUE TITLE
Improve information about use case and add presentation

### ISSUE THREAD

**Issue by jirib** [openSUSE/transactional-update#59]
Hi,

I discovered this feature but I'm surprised there's no info about an use case, ie. what is a benefit of using transactional updates. Could this be improved? And maybe it would be good to link https://events19.linuxfoundation.org/wp-content/uploads/2017/11/Transactional-Updates-with-Btrfs-and-RPM-Ignaz-Forster-SUSE.pdf in main readme file.

**Comment by laenion** [comment]
In theory we have the [Transactional Update Guide](https://kubic.opensuse.org/documentation/transactional-update-guide/transactional-update.html) which contains several use cases in chapter 1.3 (or chapter 1 in general), though I don't think a lot of people have actually read it and I'm not sure how useful it actually is. But you are correct, a link from the GitHub README file would definitely help to make it more visible at least.

**Comment by laenion** [comment]
The README has been reworked quite some time ago already as a response to this ticket, but I added a short section about the concept now - I guess that can count as the desired *use case*. Instead of the (meanwhile a bit outdated) presentation I've linked a list of talks.

Closed the issue as completed.
